# Generated by Django 4.1.7 on 2023-02-20 00:05

from django.db import migrations, models
import escola.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("rg", models.CharField(max_length=9)),
                ("cpf", models.CharField(max_length=11)),
                ("data_nascimento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_curso", models.CharField(max_length=10)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("B", escola.models.Nivel["B"]),
                            ("I", escola.models.Nivel["I"]),
                            ("A", escola.models.Nivel["A"]),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
