# Generated by Django 4.1.7 on 2023-02-22 03:59

from django.db import migrations, models
import django.db.models.deletion
import escola.models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("M", escola.models.Periodo["M"]),
                            ("V", escola.models.Periodo["V"]),
                            ("N", escola.models.Periodo["N"]),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.aluno"
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.curso"
                    ),
                ),
            ],
        ),
    ]
