# Generated by Django 4.1.7 on 2023-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0002_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("B", "Básico"), ("I", "Intermediário"), ("A", "Avançado")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="periodo",
            field=models.CharField(
                choices=[("M", "Matutino"), ("V", "Vespertino"), ("N", "Noturno")],
                default="M",
                max_length=1,
            ),
        ),
    ]
