# Generated by Django 4.1.7 on 2023-02-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0003_alter_aluno_cpf_alter_curso_nivel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
